name: gha-test2-on-selfhostedrunner

on: 
  push
  
jobs:
  b16_first_job:
    runs-on: self-hosted
    
    
    steps:
    
      - name: message
        run: echo "Welcome to GitHubactions by batch16 champs"
